### ISSUE TITLE
Which UCP Environment?

### ISSUE THREAD

**Issue by gitcoleman** [joeabbey/diver#83]
What up Dan,

Please add some sort of code to display which environment the diver user is currently working on.  Currently i have 5 UCP environments configured and i need to know where I'm working when i use this tool.

Thanks

**Comment by thebsdbox** [comment]
Added the capability to work with multiple environments:

Documentation is here https://github.com/thebsdbox/diver/tree/master/docs/ucp#working-with-multiple-ucp-sessions
