### ISSUE TITLE
UCP: Clearer warning when a ucp-bundle already exists

### ISSUE THREAD

**Issue by thebsdbox** [joeabbey/diver#88]
Currently when pulling the bundle and one already exists, diver outputs a success message and doesn't overwrite the original bundle.

**Comment by johnharris85** [comment]
I can't reproduce this. If I download a new client bundle over an old one, it overwrites. Also the [docs for](https://golang.org/pkg/os/#Create) `os.Create` say that if the file exists it will be truncated?

```
Diver, a CLI tool to interact with the Docker EE APIs
Version:  0.2
Build:    b2d851438c09b151d8b2e98300889ef36f1fe5b7
ReadOnly: false
```

UCP 3.0.2
Engine 17.06.02-ee-14
